HOSTS:
  ubuntu-server-1404-x64:
    roles:
      - master
    platform: ubuntu-server-14.04-amd64
    box: ubuntu14.04
    box_url: https://owncloud.am.ntt.eu/public.php?service=files&t=49373f7af914b12587efb4372dd5eb00&download
    hypervisor: vagrant

CONFIG:
  log_level: verbose
  type: foss
