##
# Used to create source files for ubuntu/debian apt based distro.
#
# BUG: Seems to constantly create the file, perhaps the md5 check isn't working correctly?
#
#	Usage:
#		aptsource { 'puppetlabs':
#			ensure       => present,
#  			repotype     => 'deb',
#  			uri          => "http://apt.puppetlabs.com/${lcase_os}",
#  			distribution => $::lsbdistcodename,
#  			components   => [ 'main' ],
#		}
#
#
require 'fileutils'

Puppet::Type.type(:aptsource).provide(:aptsource) do
    include Puppet::Util::Checksums

    desc "apt-source provider - manages single line repo .list files"

    def create
        File.open(sourcefile, 'w') do | file |
            file.puts header
            file.puts sourceline
	end
    end

    def destroy
        File.unlink sourcefile
    end

    def exists?
        if ! File.file?( sourcefile )
            File.new(sourcefile, "w")
            return false
        elsif compare
            return false
        end

        return false
    end

    #################################################
    # util functions
    #################################################

    def sourcefile
        listdir = '/etc/apt/sources.list.d/'
        fileext = '.list'

        listdir + resource[:sourcename] + fileext
    end

    # merge these two funcs?
    def sourceline
        "#{resource[:repotype]} #{resource[:uri]} #{resource[:distribution]} #{resource[:components]}"
    end

    def header
        "# HEADER: This file was autogenerated by puppet."
    end

    def compare
        # compare the in memory contents vs the on disk ones

        filechksum   = md5_file( sourcefile )
        memorychksum = md5( "#{sourceline}\n#{header}\n" )

        filechksum == memorychksum
    end

end
