fixtures:
  repositories:
    apache: 'https://github.com/puppetlabs/puppetlabs-apache.git'
    concat: 'https://github.com/puppetlabs/puppetlabs-concat.git'
    firewall: 'https://github.com/puppetlabs/puppetlabs-firewall.git'
    na_stdlib: 'ssh://gerrit.devcl.am.ntt.eu:29418/puppet.na_stdlib.git'
    python: 'https://github.com/counsyl/puppet-python.git'
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    sys: 'https://github.com/counsyl/puppet-sys.git'
  symlinks:
    pypiserver: "#{source_dir}"
