fixtures:
  repositories:
    apt: 'https://github.com/puppetlabs/puppetlabs-apt.git'
    cleng: "ssh://gerrit.devcl.am.ntt.eu:29418/puppet.cleng.git"
    datacat: 'https://github.com/richardc/puppet-datacat.git'
    mcollective:
      repo: "https://github.com/ntteurope/puppetlabs-mcollective.git"
      ref: "c4ce8893672ccd35d0949fd56961d9b81c39d035"
    na_stdlib: "ssh://gerrit.devcl.am.ntt.eu:29418/puppet.na_stdlib.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    na_mcollective: "#{source_dir}"
