fixtures:
  repositories:
    cleng: "ssh://gerrit.devcl.am.ntt.eu:29418/puppet.cleng.git"
    datacat: 'https://github.com/richardc/puppet-datacat.git'
    filemapper: 'https://github.com/adrienthebo/puppet-filemapper.git'
    firewall: 'https://github.com/puppetlabs/puppetlabs-firewall.git'
    mcollective:
      repo: "https://github.com/ntteurope/puppetlabs-mcollective.git"
      ref: "c4ce8893672ccd35d0949fd56961d9b81c39d035"
    na_mcollective: "ssh://gerrit.devcl.am.ntt.eu:29418/puppet.na_mcollective.git"
    na_stdlib: "ssh://gerrit.devcl.am.ntt.eu:29418/puppet.na_stdlib.git"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    yamlfile: 'https://github.com/reidmv/puppet-module-yamlfile.git'
  symlinks:
    mng_agent: "#{source_dir}"
