source "https://rubygems.org"

gem "rake"
gem "puppet", ENV['PUPPET_VERSION'] || '~> 3.4.3'
gem "puppet-lint"
gem "rspec-puppet", :git => 'https://github.com/rodjek/rspec-puppet.git'
gem "puppet-syntax"
gem "puppetlabs_spec_helper"
gem 'ntteam.ci', :git => 'ssh://gerrit.devcl.am.ntt.eu:29418/ntteam.ruby.ci'
gem "beaker"
gem "beaker-rspec"
gem "vagrant-wrapper"

group :development do
  gem 'guard-rspec'
  gem 'byebug', :platform => [:ruby_20, :ruby_21]
  gem 'debugger', :platform => [:ruby_19]
end
